development:
  adapter: postgresql
  encoding: unicode
  database: MyWebsite_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: MyWebsite_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: MyWebsite_production
  pool: 5
  username: 
  password:
